import './globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { AuctionItemsProvider } from './context/AuctionItemsContext'
import { TimerProvider } from '@/app/context/TimerContext'
import Header from './components/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Auction House',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // As the API does not have future dates, in order to show a countdown timer, we are setting today as July 1, 2025
  const now = new Date('2025-07-01').getTime()
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-full">
          <Header />
          <main className="mx-3">
            <TimerProvider serverNow={now}>
              <AuctionItemsProvider>{children}</AuctionItemsProvider>
            </TimerProvider>
          </main>
        </div>
      </body>
    </html>
  )
}
